# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20161207_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlike',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
