# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together=set([]),
        ),
    ]
