# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributetype',
            name='type',
            field=models.CharField(default='num', max_length=10),
            preserve_default=False,
        ),
    ]
