# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161130_1706'),
        ('attributes', '0002_auto_20161201_0954'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together=set([('product', 'option')]),
        ),
    ]
