# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0005_auto_20161201_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesuffix',
            name='attribute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attributes.Attribute'),
        ),
    ]
