# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customername',
            new_name='customer_name',
        ),
    ]
