# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_rating'),
        ('orders', '0002_auto_20161207_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Basket', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set([('product', 'basket')]),
        ),
    ]
