# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20161207_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Basket'),
        ),
    ]
