# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20161209_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Basket'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='orders.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
