# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161130_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='img',
        ),
    ]
