# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161201_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(height_field='height', upload_to='images/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Image'),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
